### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ongyx** [Composite1618/CompositeMemes#1]
I would like to fork your code, but there is no license so I cannot publicly re-use it. Could you add one? (I will give all due credit and attribution.)

**Comment by Composite1618** [comment]
How do I add a license on GitHub?

Ong Yong Xin <notifications@github.com>于2021年2月21日 周日上午11:32写道：

**Comment by ongyx** [comment]
Create a new file named `LICENSE` (through the main page) and press the "choose a license template" button. Pick the one you feel most suitable, and commit. I can also open a pull request to add a license if you need help.

You can also take a look at https://choosealicense.com to help you choose one.

**Comment by Composite1618** [comment]
Done.

**Comment by Composite1618** [comment]
btw are u of chinese descent(华人) by any chance, I'm from Hong Kong.

**Comment by ongyx** [comment]
Yes.
